# Generated by Django 5.2.17 on 2026-09-04 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(blank=True, db_index=True, max_length=64)),
                ('device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('success', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, choices=[('success', 'Success'), ('wrong_password', 'Wrong password'), ('device_mismatch', 'Device mismatch'), ('ip_mismatch', 'IP mismatch'), ('locked', 'Already locked')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'login attempt',
                'verbose_name_plural': 'login attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSecurityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup_ip', models.CharField(blank=True, db_index=True, max_length=64)),
                ('signup_device_fingerprint', models.CharField(blank=True, db_index=True, max_length=64)),
                ('last_login_ip', models.CharField(blank=True, max_length=64)),
                ('last_login_device_fingerprint', models.CharField(blank=True, max_length=64)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('lockout_stage', models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, '1 minute'), (2, '10 minutes'), (3, 'Permanent')], default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('permanently_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'security profile',
                'verbose_name_plural': 'security profiles',
            },
        ),
    ]
