# Generated by Django 5.2.17 on 2026-09-04 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewriteJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('humanized_text', models.TextField(blank=True)),
                ('mode', models.CharField(choices=[('sentence', 'Sentence'), ('paragraph', 'Paragraph')], default='paragraph', max_length=16)),
                ('tone', models.CharField(choices=[('casual', 'Casual'), ('conversational', 'Conversational'), ('professional', 'Professional'), ('academic', 'Academic')], default='academic', max_length=32)),
                ('strength', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('heavy', 'Heavy')], default='medium', max_length=16)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('failed', 'Failed')], default='ok', max_length=16)),
                ('error_message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrite_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='humanizer_r_user_id_1f654d_idx')],
            },
        ),
    ]
