# Generated by Django 5.2.17 on 2026-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritejob',
            name='use_case',
            field=models.CharField(choices=[('general', 'General'), ('email', 'Email'), ('linkedin', 'LinkedIn / Post'), ('report', 'Report'), ('cover_letter', 'Cover letter'), ('message', 'Slack / Message')], default='general', max_length=32),
        ),
        migrations.AlterField(
            model_name='rewritejob',
            name='tone',
            field=models.CharField(choices=[('casual', 'Casual'), ('conversational', 'Conversational'), ('professional', 'Professional'), ('academic', 'Academic')], default='professional', max_length=32),
        ),
    ]
