# Generated by Django 5.2.17 on 2026-09-04 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humanizer', '0002_rewritejob_use_case_alter_rewritejob_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewritejob',
            name='domain',
            field=models.CharField(choices=[('general', 'General'), ('coding', 'Coding / Tech'), ('finance', 'Finance'), ('business', 'Business'), ('education', 'Education'), ('sports', 'Sports'), ('politics', 'Politics'), ('healthcare', 'Healthcare'), ('creative', 'Creative'), ('marketing', 'Marketing')], default='general', max_length=32),
        ),
        migrations.AddField(
            model_name='rewritejob',
            name='style_note',
            field=models.CharField(blank=True, help_text="Optional one-line style note, e.g. 'write like a Reddit comment'.", max_length=255),
        ),
    ]
